# Generated by Django 5.2.1 on 2025-06-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_options_alter_nationality_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='actor',
            unique_together={('name', 'birthday', 'nationality')},
        ),
    ]
