# Generated by Django 5.2.1 on 2025-05-30 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Gênero', 'verbose_name_plural': 'Gêneros'},
        ),
    ]
