# Generated by Django 5.2.1 on 2025-05-30 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_resume_movie_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['release_date'], 'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
    ]
